[package]
name = "yolk-web"
version = "0.1.0"
authors = ["Avery Crespi <averycrespi@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4"
yew = "0.8"
yolk = "0.3"

[lib]
name = "yolk_web"
path = "src/lib.rs"
