[package]
name = "yolk-web"
version = "0.1.0"
authors = ["Avery Crespi <averycrespi@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
stdweb = "0.4"
yew = "0.8"
yolk = "0.3"
